Traceback (most recent call last):
  File "/Users/matteo/anaconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/matteo/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matteo/anaconda3/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matteo/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/matteo/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/matteo/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/matteo/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
## Define the Temperature
T=350;
rho=np.linspace(0.1, 6, 50) # mol / l

rho_g, Y2 = np.meshgrid(rho, y1) 
BT=np.zeros(np.size(SIGMA_mixture))

for i in np.arange(0,np.size(SIGMA_mixture)):
        BT[i]=2*np.pi*6E23*np.trapz((1-np.exp(-Gamma[:,i]/T))*np.power(r*1E-9,2),r*1E-9)

BmixT=BT[0]*Y2*Y2+BT[1]*(1-Y2)*(1-Y2)+BT[2]*Y2*(1-Y2)
        


P=T*R*rho_g+T*R*rho_g*rho_g*BmixT

Z=1+rho_g*BmixT

figure=plt.figure(figsize=(10, 8))
axes = figure.add_subplot(projection ='3d') 
axes.view_init(25, -55)
plt.draw()

surf=axes.plot_surface(1/rho_g,Y2,P,cmap=cm.coolwarm,
                       linewidth=0, antialiased=False,alpha=0.5)   

axes.set_xlabel('molar volume [l mol$^{-1}$]', fontsize=14);
axes.set_ylabel('y',fontsize=14);
axes.set_zlabel('P [atm]',fontsize=14); 
figure.colorbar(surf, shrink=0.5, aspect=10);

figure=plt.figure(figsize=(10, 8))
axes = figure.gca(projection ='3d') 
axes.view_init(25, -55)
plt.draw()

surf=axes.plot_surface(1/rho_g,Y2,Z,cmap=cm.coolwarm,
                       linewidth=0, antialiased=False,alpha=0.5)   

axes.set_xlabel('molar volume [l mol$^{-1}$]', fontsize=14);
axes.set_ylabel('y',fontsize=14);
axes.set_zlabel('compressibility factor',fontsize=14);   
figure.colorbar(surf, shrink=0.5, aspect=10);
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[6], line 33[0m
[1;32m     30[0m figure[38;5;241m.[39mcolorbar(surf, shrink[38;5;241m=[39m[38;5;241m0.5[39m, aspect[38;5;241m=[39m[38;5;241m10[39m);
[1;32m     32[0m figure[38;5;241m=[39mplt[38;5;241m.[39mfigure(figsize[38;5;241m=[39m([38;5;241m10[39m, [38;5;241m8[39m))
[0;32m---> 33[0m axes [38;5;241m=[39m [43mfigure[49m[38;5;241;43m.[39;49m[43mgca[49m[43m([49m[43mprojection[49m[43m [49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43m3d[39;49m[38;5;124;43m'[39;49m[43m)[49m 
[1;32m     34[0m axes[38;5;241m.[39mview_init([38;5;241m25[39m, [38;5;241m-[39m[38;5;241m55[39m)
[1;32m     35[0m plt[38;5;241m.[39mdraw()

[0;31mTypeError[0m: FigureBase.gca() got an unexpected keyword argument 'projection'

